name: Emojify PR Title

on: pull_request

jobs:
  emojify-pr-title:
    runs-on: ubuntu-latest
    name: Emojify PR Title
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emojify PR Title
        uses: pineapplelol/emojify-pr-title@v1.5.3
        with:
          use-emoji-map: true
          emoji-map: https://raw.githubusercontent.com/hack4impact-uiuc/falling-fruit/bump-emojify-pr/.github/workflows/mappings.json
